#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Jihun`s Dev Note

<<<<<<< HEAD
# Short bio or description (displayed in the header)
description: Embedded Linux Developer
=======
# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : "google-gtag" # false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-151933339-1"
    anonymize_ip         : # true, false (default)

# Site Author
author:
  name             : "Jihun Kim"
  avatar           : "/assets/images/bio/bio-photo.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Embedded Linux Developer"
  location         : "South korea"
  email            : "jihun.dev@gmail.com"
  uri              :
  home             : # null (default), "absolute or relative url to link to author home"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "jihundev"
  gitlab           : "jihundev"
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "jihun-kim" # "john-doe-12345678" (the last part of your profile url, e.g. https://www.linkedin.com/in/john-doe-12345678)
  pinterest        :
  soundcloud       :
  stackoverflow    : "5311181/jihun-kim" # "123456/username" (the last part of your profile url, e.g. https://stackoverflow.com/users/123456/username)
  steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          : # "https://youtube.com/c/MichaelRoseDesign"
>>>>>>> master

#
# Flags below are optional
#

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars3.githubusercontent.com/u/5136900?s=400&u=52f31a1707a2f0b3fbd30c3b4a0bdd2ae49c1ceb&v=4


# Tabs in header. There are 'Blog', 'About', 'Archive', 'Tags'
# and URL Link(e.g. 'Theme' tab below) tabs. If you don't need one, just delete
# it from the list(Delete '- name: ' and 'url: ', too!)
navigation:
  - name: Blog
    url: /
#  - name: About
#    url: /about
  - name: Archive
    url: /archive
  - name: Tags
    url: /tags

# Pagination
paginate: 7

# Includes an icon in the footer for each username you enter
footer-links:
  behance: # https://www.behance.net/<username>
  dribbble:
  email: jihun.dev@gmail.com
  facebook:
  flickr:
  github: jihundev
  googleplus: # anything in your profile username that comes after plus.google.com/
  instagram:
  linkedin: jihun-kim
  pinterest:
  rss: # just type anything here for a working RSS icon
  stackoverflow: 5311181/jihun-kim
  tumblr: # https://<username>.tumblr.com
  twitter:
  youtube: # channel/<your_long_string> or user/<user-name>

# Text under the icons in footer
footer-text: © 2019 Jihun Kim. Powered by Jekyll & Kiko Now

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: jihun-1.disqus.com

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-151933339-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl:

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
